### ISSUE TITLE
SpartanToolkit is crashing game on loading

### ISSUE THREAD

**Issue by gorroii** [KreloX/SpartanAddonToolkit#2]
[latest.log](https://github.com/user-attachments/files/16103235/latest.log)

If uninstalled it is not crashing and working correctly

Forge 47.3.0

Minecraft 1.20.1

**Comment by SuperStefan97** [comment]
Same here!
[crash-2024-07-04_17.09.08-client.txt](https://github.com/user-attachments/files/16103317/crash-2024-07-04_17.09.08-client.txt)

**Comment by rloelol** [comment]
I am also having this issue, I'm running 1.19.2 and this mod crashes the game on startup, but is depended on by other mods.
[latest.log](https://github.com/user-attachments/files/16103827/latest.log)

**Comment by KreloX** [comment]
I didn't recieve a notification about this issue being reported so I'm closing it now. I believe this was fixed in 1.2.2, if not feel free to reopen this
